obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.32,0],[0.20,0.3],[-0.42,0],[0.20,-0.3]]
inflation_radius: 0.45
max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
