controller_frequency: 3.0

TrajectoryPlannerROS:
   max_vel_x: 0.3
   min_vel_x: 0.1
   max_rotational_vel: 1.0
   min_vel_theta: 0.5
   acc_lim_x: 2.5
   acc_lim_y: 2.5
   acc_lim_th: 3.2

   holonomic_robot: true
   yaw_goal_tolerance: 6 # about 6 degrees
   xy_goal_tolerance: 0.1  # 10 cm
   pdist_scale: 0.8
   gdist_scale: 0.6

   occdist_scale: 0.1
   oscillation_reset_dist: 0.05
  
   sim_time: 1.0
   dwa: ture
