controller_frequency: 3.0

TrajectoryPlannerROS:
   max_vel_x: 0.3
   min_vel_x: 0.1
   max_rotational_vel: 1.0
   min_vel_theta: -1.0
   acc_lim_x: 2.5
   acc_lim_y: 2.5
   acc_lim_theta: 3.2

   holonomic_robot: true
   yaw_goal_tolerance: 0.1 # about 6 degrees
   xy_goal_tolerance: 0.2  # 10 cm
   pdist_scale: 0.8
   gdist_scale: 0.6
   meter_scoring: true

   heading_lookahead: 0.325
   heading_scoring: false
   heading_scoring_timestep: 0.8
   occdist_scale: 0.1
   oscillation_reset_dist: 0.05
   publish_cost_grid_pc: false
   prune_plan: true

   sim_time: 1.0
   sim_granularity: 0.025
   angular_sim_granularity: 0.025
   vx_samples: 8
   vtheta_samples: 20
   dwa: false
   simple_attractor: false
