obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.28,0],[0.16,0.3],[-0.38,0],[0.16,-0.3]]
inflation_radius: 0.15
max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
