local_costmap:
   global_frame: /odom
   robot_base_frame: /base_link
   update_frequency: 3.0
   publish_frequency: 1.0
   static_map: false
   rolling_window: false
   width: 5.0
   height: 5.0
   resolution: 0.01
